name: Build and push docker container for frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"
  REGISTRY_URL: "public.ecr.aws/a2x9x9v5/global-triangles/frontend"
  AWS_ACCOUNT_ID: "454127780570"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v3

    - name: Get AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    - run: aws sts get-caller-identity

    - name: Login to AWS container registry
      run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: public.ecr.aws/a2x9x9v5/global-triangles/frontend:latest
